/*
Navicat MySQL Data Transfer

Source Server         : local
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : imooc

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2017-04-10 16:50:54
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `deepcate`
-- ----------------------------
DROP TABLE IF EXISTS `deepcate`;
CREATE TABLE `deepcate` (
  `id` int(10) unsigned NOT NULL,
  `pid` int(11) unsigned NOT NULL,
  `catename` varchar(30) NOT NULL,
  `cateorder` int(11) unsigned NOT NULL DEFAULT '0',
  `createtime` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of deepcate
-- ----------------------------
INSERT INTO `deepcate` VALUES ('1', '0', '新闻', '0', '0');
INSERT INTO `deepcate` VALUES ('2', '0', '图片', '0', '0');
INSERT INTO `deepcate` VALUES ('3', '1', '国内新闻', '0', '0');
INSERT INTO `deepcate` VALUES ('4', '1', '国际新闻', '0', '0');
INSERT INTO `deepcate` VALUES ('5', '3', '北京新闻', '0', '0');
INSERT INTO `deepcate` VALUES ('6', '4', '美国新闻', '0', '0');
INSERT INTO `deepcate` VALUES ('7', '2', '美女图片', '0', '0');
INSERT INTO `deepcate` VALUES ('8', '2', '风景图片', '0', '0');
INSERT INTO `deepcate` VALUES ('9', '7', '日韩明星', '0', '0');
INSERT INTO `deepcate` VALUES ('10', '9', '日本AV', '0', '0');

-- ----------------------------
-- Table structure for `likecate`
-- ----------------------------
DROP TABLE IF EXISTS `likecate`;
CREATE TABLE `likecate` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `path` varchar(200) NOT NULL,
  `catename` varchar(30) NOT NULL,
  `cateorder` int(10) NOT NULL DEFAULT '0',
  `createtime` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of likecate
-- ----------------------------
INSERT INTO `likecate` VALUES ('1', '', '手机', '0', '0');
INSERT INTO `likecate` VALUES ('2', '1', '功能手机', '0', '0');
INSERT INTO `likecate` VALUES ('3', '1,2', '老人手机', '0', '0');
INSERT INTO `likecate` VALUES ('4', '1,2', '儿童手机', '0', '0');
INSERT INTO `likecate` VALUES ('5', '1', '智能手机', '0', '0');
INSERT INTO `likecate` VALUES ('6', '1,5', 'Android手机', '0', '0');
INSERT INTO `likecate` VALUES ('7', '1,5', 'IOS手机', '0', '0');
INSERT INTO `likecate` VALUES ('8', '1,5', 'Winphone手机', '0', '0');
INSERT INTO `likecate` VALUES ('9', '1,2,4', '色盲手机', '0', '0');
INSERT INTO `likecate` VALUES ('10', '1,2,3', '大字手机', '0', '0');

-- ----------------------------
-- Table structure for `mail`
-- ----------------------------
DROP TABLE IF EXISTS `mail`;
CREATE TABLE `mail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(30) NOT NULL,
  `password` varchar(32) NOT NULL,
  `email` varchar(30) NOT NULL,
  `token` varchar(50) NOT NULL,
  `token_exptime` int(10) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `regtime` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of mail
-- ----------------------------
INSERT INTO `mail` VALUES ('1', '常鹏飞', 'e6870a5703bfc590b2e6439acd2e92d3', '877040117@qq.com', '62716f26572818fcbbb5c1af5939d0f8', '1480902639', '1', '1480816239');

-- ----------------------------
-- Table structure for `shop_cart`
-- ----------------------------
DROP TABLE IF EXISTS `shop_cart`;
CREATE TABLE `shop_cart` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `productid` int(20) NOT NULL,
  `userid` int(20) NOT NULL,
  `num` int(10) NOT NULL,
  `price` float(8,2) NOT NULL,
  `createtime` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of shop_cart
-- ----------------------------

-- ----------------------------
-- Table structure for `shop_product`
-- ----------------------------
DROP TABLE IF EXISTS `shop_product`;
CREATE TABLE `shop_product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` char(255) NOT NULL,
  `describe` char(255) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `originalprice` decimal(10,2) NOT NULL,
  `inventory` int(11) NOT NULL,
  `categoryid` int(11) NOT NULL,
  `brandid` int(11) NOT NULL,
  `adminid` int(11) NOT NULL,
  `ishot` int(11) NOT NULL,
  `isputaway` smallint(6) NOT NULL,
  `isonsale` smallint(6) NOT NULL,
  `onsaleprice` decimal(10,2) NOT NULL,
  `cover` char(200) NOT NULL,
  `updatetime` datetime NOT NULL,
  `createtime` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of shop_product
-- ----------------------------
INSERT INTO `shop_product` VALUES ('1', 'Apple/苹果 白色运动表带', null, '2588.00', '2588.00', '100', '1', '1', '1', '1', '1', '0', '0.00', '/resource/1.jpg', '2015-12-20 17:18:50', '1417013251');
INSERT INTO `shop_product` VALUES ('2', '苹果Apple Watch 薰衣草色表带', null, '2436.00', '2888.00', '100', '1', '1', '1', '1', '1', '0', '0.00', '/resource/2.jpg', '2015-12-20 17:18:50', '1447033051');

-- ----------------------------
-- Table structure for `test2`
-- ----------------------------
DROP TABLE IF EXISTS `test2`;
CREATE TABLE `test2` (
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of test2
-- ----------------------------
INSERT INTO `test2` VALUES ('1');
INSERT INTO `test2` VALUES ('2');
INSERT INTO `test2` VALUES ('3');
INSERT INTO `test2` VALUES ('4');
INSERT INTO `test2` VALUES ('5');
INSERT INTO `test2` VALUES ('6');
INSERT INTO `test2` VALUES ('7');
INSERT INTO `test2` VALUES ('8');
INSERT INTO `test2` VALUES ('9');
INSERT INTO `test2` VALUES ('10');
INSERT INTO `test2` VALUES ('11');
INSERT INTO `test2` VALUES ('12');
INSERT INTO `test2` VALUES ('13');
INSERT INTO `test2` VALUES ('14');
INSERT INTO `test2` VALUES ('15');
INSERT INTO `test2` VALUES ('16');
INSERT INTO `test2` VALUES ('17');
INSERT INTO `test2` VALUES ('18');
INSERT INTO `test2` VALUES ('19');
INSERT INTO `test2` VALUES ('20');
INSERT INTO `test2` VALUES ('21');
INSERT INTO `test2` VALUES ('22');
INSERT INTO `test2` VALUES ('23');
INSERT INTO `test2` VALUES ('24');
INSERT INTO `test2` VALUES ('25');
INSERT INTO `test2` VALUES ('26');
INSERT INTO `test2` VALUES ('27');
INSERT INTO `test2` VALUES ('28');
INSERT INTO `test2` VALUES ('29');
INSERT INTO `test2` VALUES ('30');
INSERT INTO `test2` VALUES ('31');
INSERT INTO `test2` VALUES ('32');
INSERT INTO `test2` VALUES ('33');
INSERT INTO `test2` VALUES ('34');
INSERT INTO `test2` VALUES ('35');
INSERT INTO `test2` VALUES ('36');
INSERT INTO `test2` VALUES ('37');
INSERT INTO `test2` VALUES ('38');
INSERT INTO `test2` VALUES ('39');
INSERT INTO `test2` VALUES ('40');
INSERT INTO `test2` VALUES ('41');
INSERT INTO `test2` VALUES ('42');
INSERT INTO `test2` VALUES ('43');
INSERT INTO `test2` VALUES ('44');
INSERT INTO `test2` VALUES ('45');
INSERT INTO `test2` VALUES ('46');
INSERT INTO `test2` VALUES ('47');
INSERT INTO `test2` VALUES ('48');
INSERT INTO `test2` VALUES ('49');
INSERT INTO `test2` VALUES ('50');
INSERT INTO `test2` VALUES ('51');
INSERT INTO `test2` VALUES ('52');
INSERT INTO `test2` VALUES ('53');
INSERT INTO `test2` VALUES ('54');
INSERT INTO `test2` VALUES ('55');
INSERT INTO `test2` VALUES ('56');
INSERT INTO `test2` VALUES ('57');
INSERT INTO `test2` VALUES ('58');
INSERT INTO `test2` VALUES ('59');
INSERT INTO `test2` VALUES ('60');
INSERT INTO `test2` VALUES ('61');
INSERT INTO `test2` VALUES ('62');
INSERT INTO `test2` VALUES ('63');
INSERT INTO `test2` VALUES ('64');
INSERT INTO `test2` VALUES ('65');
INSERT INTO `test2` VALUES ('66');
INSERT INTO `test2` VALUES ('67');
INSERT INTO `test2` VALUES ('68');
INSERT INTO `test2` VALUES ('69');
INSERT INTO `test2` VALUES ('70');
INSERT INTO `test2` VALUES ('71');
INSERT INTO `test2` VALUES ('72');
INSERT INTO `test2` VALUES ('73');
INSERT INTO `test2` VALUES ('74');
INSERT INTO `test2` VALUES ('75');
INSERT INTO `test2` VALUES ('76');
INSERT INTO `test2` VALUES ('77');
INSERT INTO `test2` VALUES ('78');
INSERT INTO `test2` VALUES ('79');
INSERT INTO `test2` VALUES ('80');
INSERT INTO `test2` VALUES ('81');
INSERT INTO `test2` VALUES ('82');
INSERT INTO `test2` VALUES ('83');
INSERT INTO `test2` VALUES ('84');
INSERT INTO `test2` VALUES ('85');
INSERT INTO `test2` VALUES ('86');
INSERT INTO `test2` VALUES ('87');
INSERT INTO `test2` VALUES ('88');
INSERT INTO `test2` VALUES ('89');
INSERT INTO `test2` VALUES ('90');
INSERT INTO `test2` VALUES ('91');
INSERT INTO `test2` VALUES ('92');
INSERT INTO `test2` VALUES ('93');
INSERT INTO `test2` VALUES ('94');
INSERT INTO `test2` VALUES ('95');
INSERT INTO `test2` VALUES ('96');
INSERT INTO `test2` VALUES ('97');
INSERT INTO `test2` VALUES ('98');
INSERT INTO `test2` VALUES ('99');
INSERT INTO `test2` VALUES ('100');
INSERT INTO `test2` VALUES ('101');
INSERT INTO `test2` VALUES ('102');
INSERT INTO `test2` VALUES ('103');
INSERT INTO `test2` VALUES ('104');
INSERT INTO `test2` VALUES ('105');
INSERT INTO `test2` VALUES ('106');
INSERT INTO `test2` VALUES ('107');
INSERT INTO `test2` VALUES ('108');
INSERT INTO `test2` VALUES ('109');
INSERT INTO `test2` VALUES ('110');
INSERT INTO `test2` VALUES ('111');
INSERT INTO `test2` VALUES ('112');
INSERT INTO `test2` VALUES ('113');
INSERT INTO `test2` VALUES ('114');
INSERT INTO `test2` VALUES ('115');
INSERT INTO `test2` VALUES ('116');
INSERT INTO `test2` VALUES ('117');
INSERT INTO `test2` VALUES ('118');
INSERT INTO `test2` VALUES ('119');
INSERT INTO `test2` VALUES ('120');
INSERT INTO `test2` VALUES ('121');
INSERT INTO `test2` VALUES ('122');
INSERT INTO `test2` VALUES ('123');
INSERT INTO `test2` VALUES ('124');
INSERT INTO `test2` VALUES ('125');
INSERT INTO `test2` VALUES ('126');
INSERT INTO `test2` VALUES ('127');
INSERT INTO `test2` VALUES ('128');
INSERT INTO `test2` VALUES ('129');
INSERT INTO `test2` VALUES ('130');
INSERT INTO `test2` VALUES ('131');
INSERT INTO `test2` VALUES ('132');
INSERT INTO `test2` VALUES ('133');
INSERT INTO `test2` VALUES ('134');
INSERT INTO `test2` VALUES ('135');
INSERT INTO `test2` VALUES ('136');
INSERT INTO `test2` VALUES ('137');
INSERT INTO `test2` VALUES ('138');
INSERT INTO `test2` VALUES ('139');
INSERT INTO `test2` VALUES ('140');
INSERT INTO `test2` VALUES ('141');
INSERT INTO `test2` VALUES ('142');
INSERT INTO `test2` VALUES ('143');
INSERT INTO `test2` VALUES ('144');
INSERT INTO `test2` VALUES ('145');
INSERT INTO `test2` VALUES ('146');
INSERT INTO `test2` VALUES ('147');
INSERT INTO `test2` VALUES ('148');
INSERT INTO `test2` VALUES ('149');
INSERT INTO `test2` VALUES ('150');
INSERT INTO `test2` VALUES ('151');
INSERT INTO `test2` VALUES ('152');
INSERT INTO `test2` VALUES ('153');
INSERT INTO `test2` VALUES ('154');
INSERT INTO `test2` VALUES ('155');
INSERT INTO `test2` VALUES ('156');
INSERT INTO `test2` VALUES ('157');
INSERT INTO `test2` VALUES ('158');
INSERT INTO `test2` VALUES ('159');
INSERT INTO `test2` VALUES ('160');
INSERT INTO `test2` VALUES ('161');
INSERT INTO `test2` VALUES ('162');
INSERT INTO `test2` VALUES ('163');
INSERT INTO `test2` VALUES ('164');
INSERT INTO `test2` VALUES ('165');
INSERT INTO `test2` VALUES ('166');
INSERT INTO `test2` VALUES ('167');
INSERT INTO `test2` VALUES ('168');
INSERT INTO `test2` VALUES ('169');
INSERT INTO `test2` VALUES ('170');
INSERT INTO `test2` VALUES ('171');
INSERT INTO `test2` VALUES ('172');
INSERT INTO `test2` VALUES ('173');
INSERT INTO `test2` VALUES ('174');
INSERT INTO `test2` VALUES ('175');
INSERT INTO `test2` VALUES ('176');
INSERT INTO `test2` VALUES ('177');
INSERT INTO `test2` VALUES ('178');
INSERT INTO `test2` VALUES ('179');
INSERT INTO `test2` VALUES ('180');
INSERT INTO `test2` VALUES ('181');
INSERT INTO `test2` VALUES ('182');
INSERT INTO `test2` VALUES ('183');
INSERT INTO `test2` VALUES ('184');
INSERT INTO `test2` VALUES ('185');
INSERT INTO `test2` VALUES ('186');
INSERT INTO `test2` VALUES ('187');
INSERT INTO `test2` VALUES ('188');
INSERT INTO `test2` VALUES ('189');
INSERT INTO `test2` VALUES ('190');
INSERT INTO `test2` VALUES ('191');
INSERT INTO `test2` VALUES ('192');
INSERT INTO `test2` VALUES ('193');
INSERT INTO `test2` VALUES ('194');
INSERT INTO `test2` VALUES ('195');
INSERT INTO `test2` VALUES ('196');
INSERT INTO `test2` VALUES ('197');
INSERT INTO `test2` VALUES ('198');
INSERT INTO `test2` VALUES ('199');
INSERT INTO `test2` VALUES ('200');
INSERT INTO `test2` VALUES ('201');
INSERT INTO `test2` VALUES ('202');
INSERT INTO `test2` VALUES ('203');
INSERT INTO `test2` VALUES ('204');
INSERT INTO `test2` VALUES ('205');
INSERT INTO `test2` VALUES ('206');
INSERT INTO `test2` VALUES ('207');
INSERT INTO `test2` VALUES ('208');
INSERT INTO `test2` VALUES ('209');
INSERT INTO `test2` VALUES ('210');
INSERT INTO `test2` VALUES ('211');
INSERT INTO `test2` VALUES ('212');
INSERT INTO `test2` VALUES ('213');
INSERT INTO `test2` VALUES ('214');
INSERT INTO `test2` VALUES ('215');
INSERT INTO `test2` VALUES ('216');
INSERT INTO `test2` VALUES ('217');
INSERT INTO `test2` VALUES ('218');
INSERT INTO `test2` VALUES ('219');
INSERT INTO `test2` VALUES ('220');
INSERT INTO `test2` VALUES ('221');
INSERT INTO `test2` VALUES ('222');
INSERT INTO `test2` VALUES ('223');
INSERT INTO `test2` VALUES ('224');
INSERT INTO `test2` VALUES ('225');
INSERT INTO `test2` VALUES ('226');
INSERT INTO `test2` VALUES ('227');
INSERT INTO `test2` VALUES ('228');
INSERT INTO `test2` VALUES ('229');
INSERT INTO `test2` VALUES ('230');
INSERT INTO `test2` VALUES ('231');
INSERT INTO `test2` VALUES ('232');
INSERT INTO `test2` VALUES ('233');
INSERT INTO `test2` VALUES ('234');
INSERT INTO `test2` VALUES ('235');
INSERT INTO `test2` VALUES ('236');
INSERT INTO `test2` VALUES ('237');
INSERT INTO `test2` VALUES ('238');
INSERT INTO `test2` VALUES ('239');
INSERT INTO `test2` VALUES ('240');
INSERT INTO `test2` VALUES ('241');
INSERT INTO `test2` VALUES ('242');
INSERT INTO `test2` VALUES ('243');
INSERT INTO `test2` VALUES ('244');
INSERT INTO `test2` VALUES ('245');
INSERT INTO `test2` VALUES ('246');
INSERT INTO `test2` VALUES ('247');
INSERT INTO `test2` VALUES ('248');
INSERT INTO `test2` VALUES ('249');
INSERT INTO `test2` VALUES ('250');
INSERT INTO `test2` VALUES ('251');
INSERT INTO `test2` VALUES ('252');
INSERT INTO `test2` VALUES ('253');
INSERT INTO `test2` VALUES ('254');
INSERT INTO `test2` VALUES ('255');
INSERT INTO `test2` VALUES ('256');
INSERT INTO `test2` VALUES ('257');
INSERT INTO `test2` VALUES ('258');
INSERT INTO `test2` VALUES ('259');
INSERT INTO `test2` VALUES ('260');
INSERT INTO `test2` VALUES ('261');
INSERT INTO `test2` VALUES ('262');
INSERT INTO `test2` VALUES ('263');
INSERT INTO `test2` VALUES ('264');
INSERT INTO `test2` VALUES ('265');
INSERT INTO `test2` VALUES ('266');
INSERT INTO `test2` VALUES ('267');
INSERT INTO `test2` VALUES ('268');
INSERT INTO `test2` VALUES ('269');
INSERT INTO `test2` VALUES ('270');
INSERT INTO `test2` VALUES ('271');
INSERT INTO `test2` VALUES ('272');
INSERT INTO `test2` VALUES ('273');
INSERT INTO `test2` VALUES ('274');
INSERT INTO `test2` VALUES ('275');
INSERT INTO `test2` VALUES ('276');
INSERT INTO `test2` VALUES ('277');
INSERT INTO `test2` VALUES ('278');
INSERT INTO `test2` VALUES ('279');
INSERT INTO `test2` VALUES ('280');
INSERT INTO `test2` VALUES ('281');
INSERT INTO `test2` VALUES ('282');
INSERT INTO `test2` VALUES ('283');
INSERT INTO `test2` VALUES ('284');
INSERT INTO `test2` VALUES ('285');
INSERT INTO `test2` VALUES ('286');
INSERT INTO `test2` VALUES ('287');
INSERT INTO `test2` VALUES ('288');
INSERT INTO `test2` VALUES ('289');
INSERT INTO `test2` VALUES ('290');
INSERT INTO `test2` VALUES ('291');
INSERT INTO `test2` VALUES ('292');
INSERT INTO `test2` VALUES ('293');
INSERT INTO `test2` VALUES ('294');
INSERT INTO `test2` VALUES ('295');
INSERT INTO `test2` VALUES ('296');
INSERT INTO `test2` VALUES ('297');
INSERT INTO `test2` VALUES ('298');
INSERT INTO `test2` VALUES ('299');
INSERT INTO `test2` VALUES ('300');
INSERT INTO `test2` VALUES ('301');
INSERT INTO `test2` VALUES ('302');
INSERT INTO `test2` VALUES ('303');
INSERT INTO `test2` VALUES ('304');
INSERT INTO `test2` VALUES ('305');
INSERT INTO `test2` VALUES ('306');
INSERT INTO `test2` VALUES ('307');
INSERT INTO `test2` VALUES ('308');
INSERT INTO `test2` VALUES ('309');
INSERT INTO `test2` VALUES ('310');
INSERT INTO `test2` VALUES ('311');
INSERT INTO `test2` VALUES ('312');
INSERT INTO `test2` VALUES ('313');
INSERT INTO `test2` VALUES ('314');
INSERT INTO `test2` VALUES ('315');
INSERT INTO `test2` VALUES ('316');
INSERT INTO `test2` VALUES ('317');
INSERT INTO `test2` VALUES ('318');
INSERT INTO `test2` VALUES ('319');
INSERT INTO `test2` VALUES ('320');
INSERT INTO `test2` VALUES ('321');
INSERT INTO `test2` VALUES ('322');
INSERT INTO `test2` VALUES ('323');
INSERT INTO `test2` VALUES ('324');
INSERT INTO `test2` VALUES ('325');
INSERT INTO `test2` VALUES ('326');
INSERT INTO `test2` VALUES ('327');
INSERT INTO `test2` VALUES ('328');
INSERT INTO `test2` VALUES ('329');
INSERT INTO `test2` VALUES ('330');
INSERT INTO `test2` VALUES ('331');
INSERT INTO `test2` VALUES ('332');
INSERT INTO `test2` VALUES ('333');
INSERT INTO `test2` VALUES ('334');
INSERT INTO `test2` VALUES ('335');
INSERT INTO `test2` VALUES ('336');
INSERT INTO `test2` VALUES ('337');
INSERT INTO `test2` VALUES ('338');
INSERT INTO `test2` VALUES ('339');
INSERT INTO `test2` VALUES ('340');
INSERT INTO `test2` VALUES ('341');
INSERT INTO `test2` VALUES ('342');
INSERT INTO `test2` VALUES ('343');
INSERT INTO `test2` VALUES ('344');
INSERT INTO `test2` VALUES ('345');
INSERT INTO `test2` VALUES ('346');
INSERT INTO `test2` VALUES ('347');
INSERT INTO `test2` VALUES ('348');
INSERT INTO `test2` VALUES ('349');
INSERT INTO `test2` VALUES ('350');
INSERT INTO `test2` VALUES ('351');
INSERT INTO `test2` VALUES ('352');
INSERT INTO `test2` VALUES ('353');
INSERT INTO `test2` VALUES ('354');
INSERT INTO `test2` VALUES ('355');
INSERT INTO `test2` VALUES ('356');
INSERT INTO `test2` VALUES ('357');
INSERT INTO `test2` VALUES ('358');
INSERT INTO `test2` VALUES ('359');
INSERT INTO `test2` VALUES ('360');
INSERT INTO `test2` VALUES ('361');
INSERT INTO `test2` VALUES ('362');
INSERT INTO `test2` VALUES ('363');
INSERT INTO `test2` VALUES ('364');
INSERT INTO `test2` VALUES ('365');
INSERT INTO `test2` VALUES ('366');
INSERT INTO `test2` VALUES ('367');
INSERT INTO `test2` VALUES ('368');
INSERT INTO `test2` VALUES ('369');
INSERT INTO `test2` VALUES ('370');
INSERT INTO `test2` VALUES ('371');
INSERT INTO `test2` VALUES ('372');
INSERT INTO `test2` VALUES ('373');
INSERT INTO `test2` VALUES ('374');
INSERT INTO `test2` VALUES ('375');
INSERT INTO `test2` VALUES ('376');
INSERT INTO `test2` VALUES ('377');
INSERT INTO `test2` VALUES ('378');
INSERT INTO `test2` VALUES ('379');
INSERT INTO `test2` VALUES ('380');
INSERT INTO `test2` VALUES ('381');
INSERT INTO `test2` VALUES ('382');
INSERT INTO `test2` VALUES ('383');
INSERT INTO `test2` VALUES ('384');
INSERT INTO `test2` VALUES ('385');
INSERT INTO `test2` VALUES ('386');
INSERT INTO `test2` VALUES ('387');
INSERT INTO `test2` VALUES ('388');
INSERT INTO `test2` VALUES ('389');
INSERT INTO `test2` VALUES ('390');
INSERT INTO `test2` VALUES ('391');
INSERT INTO `test2` VALUES ('392');
INSERT INTO `test2` VALUES ('393');
INSERT INTO `test2` VALUES ('394');
INSERT INTO `test2` VALUES ('395');
INSERT INTO `test2` VALUES ('396');
INSERT INTO `test2` VALUES ('397');
INSERT INTO `test2` VALUES ('398');
INSERT INTO `test2` VALUES ('399');
INSERT INTO `test2` VALUES ('400');
INSERT INTO `test2` VALUES ('401');
INSERT INTO `test2` VALUES ('402');
INSERT INTO `test2` VALUES ('403');
INSERT INTO `test2` VALUES ('404');
INSERT INTO `test2` VALUES ('405');
INSERT INTO `test2` VALUES ('406');
INSERT INTO `test2` VALUES ('407');
INSERT INTO `test2` VALUES ('408');
INSERT INTO `test2` VALUES ('409');
INSERT INTO `test2` VALUES ('410');
INSERT INTO `test2` VALUES ('411');
INSERT INTO `test2` VALUES ('412');
INSERT INTO `test2` VALUES ('413');
INSERT INTO `test2` VALUES ('414');
INSERT INTO `test2` VALUES ('415');
INSERT INTO `test2` VALUES ('416');
INSERT INTO `test2` VALUES ('417');
INSERT INTO `test2` VALUES ('418');
INSERT INTO `test2` VALUES ('419');
INSERT INTO `test2` VALUES ('420');
INSERT INTO `test2` VALUES ('421');
INSERT INTO `test2` VALUES ('422');
INSERT INTO `test2` VALUES ('423');
INSERT INTO `test2` VALUES ('424');
INSERT INTO `test2` VALUES ('425');
INSERT INTO `test2` VALUES ('426');
INSERT INTO `test2` VALUES ('427');
INSERT INTO `test2` VALUES ('428');
INSERT INTO `test2` VALUES ('429');
INSERT INTO `test2` VALUES ('430');
INSERT INTO `test2` VALUES ('431');
INSERT INTO `test2` VALUES ('432');
INSERT INTO `test2` VALUES ('433');
INSERT INTO `test2` VALUES ('434');
INSERT INTO `test2` VALUES ('435');
INSERT INTO `test2` VALUES ('436');
INSERT INTO `test2` VALUES ('437');
INSERT INTO `test2` VALUES ('438');
INSERT INTO `test2` VALUES ('439');
INSERT INTO `test2` VALUES ('440');
INSERT INTO `test2` VALUES ('441');
INSERT INTO `test2` VALUES ('442');
INSERT INTO `test2` VALUES ('443');
INSERT INTO `test2` VALUES ('444');
INSERT INTO `test2` VALUES ('445');
INSERT INTO `test2` VALUES ('446');
INSERT INTO `test2` VALUES ('447');
INSERT INTO `test2` VALUES ('448');
INSERT INTO `test2` VALUES ('449');
INSERT INTO `test2` VALUES ('450');
INSERT INTO `test2` VALUES ('451');
INSERT INTO `test2` VALUES ('452');
INSERT INTO `test2` VALUES ('453');
INSERT INTO `test2` VALUES ('454');
INSERT INTO `test2` VALUES ('455');
INSERT INTO `test2` VALUES ('456');
INSERT INTO `test2` VALUES ('457');
INSERT INTO `test2` VALUES ('458');
INSERT INTO `test2` VALUES ('459');
INSERT INTO `test2` VALUES ('460');
INSERT INTO `test2` VALUES ('461');
INSERT INTO `test2` VALUES ('462');
INSERT INTO `test2` VALUES ('463');
INSERT INTO `test2` VALUES ('464');
INSERT INTO `test2` VALUES ('465');
INSERT INTO `test2` VALUES ('466');
INSERT INTO `test2` VALUES ('467');
INSERT INTO `test2` VALUES ('468');
INSERT INTO `test2` VALUES ('469');
INSERT INTO `test2` VALUES ('470');
INSERT INTO `test2` VALUES ('471');
INSERT INTO `test2` VALUES ('472');
INSERT INTO `test2` VALUES ('473');
INSERT INTO `test2` VALUES ('474');
INSERT INTO `test2` VALUES ('475');
INSERT INTO `test2` VALUES ('476');
INSERT INTO `test2` VALUES ('477');
INSERT INTO `test2` VALUES ('478');
INSERT INTO `test2` VALUES ('479');
INSERT INTO `test2` VALUES ('480');
INSERT INTO `test2` VALUES ('481');
INSERT INTO `test2` VALUES ('482');
INSERT INTO `test2` VALUES ('483');
INSERT INTO `test2` VALUES ('484');
INSERT INTO `test2` VALUES ('485');
INSERT INTO `test2` VALUES ('486');
INSERT INTO `test2` VALUES ('487');
INSERT INTO `test2` VALUES ('488');
INSERT INTO `test2` VALUES ('489');
INSERT INTO `test2` VALUES ('490');
INSERT INTO `test2` VALUES ('491');
INSERT INTO `test2` VALUES ('492');
INSERT INTO `test2` VALUES ('493');
INSERT INTO `test2` VALUES ('494');
INSERT INTO `test2` VALUES ('495');
INSERT INTO `test2` VALUES ('496');
INSERT INTO `test2` VALUES ('497');
INSERT INTO `test2` VALUES ('498');
INSERT INTO `test2` VALUES ('499');
INSERT INTO `test2` VALUES ('500');
INSERT INTO `test2` VALUES ('1');
INSERT INTO `test2` VALUES ('2');
INSERT INTO `test2` VALUES ('3');
INSERT INTO `test2` VALUES ('4');
INSERT INTO `test2` VALUES ('5');
INSERT INTO `test2` VALUES ('6');
INSERT INTO `test2` VALUES ('7');
INSERT INTO `test2` VALUES ('8');
INSERT INTO `test2` VALUES ('9');
INSERT INTO `test2` VALUES ('10');
INSERT INTO `test2` VALUES ('11');
INSERT INTO `test2` VALUES ('12');
INSERT INTO `test2` VALUES ('13');
INSERT INTO `test2` VALUES ('14');
INSERT INTO `test2` VALUES ('15');
INSERT INTO `test2` VALUES ('16');
INSERT INTO `test2` VALUES ('17');
INSERT INTO `test2` VALUES ('18');
INSERT INTO `test2` VALUES ('19');
INSERT INTO `test2` VALUES ('20');
INSERT INTO `test2` VALUES ('21');
INSERT INTO `test2` VALUES ('22');
INSERT INTO `test2` VALUES ('23');
INSERT INTO `test2` VALUES ('24');
INSERT INTO `test2` VALUES ('25');
INSERT INTO `test2` VALUES ('26');
INSERT INTO `test2` VALUES ('27');
INSERT INTO `test2` VALUES ('28');
INSERT INTO `test2` VALUES ('29');
INSERT INTO `test2` VALUES ('30');
INSERT INTO `test2` VALUES ('31');
INSERT INTO `test2` VALUES ('32');
INSERT INTO `test2` VALUES ('33');
INSERT INTO `test2` VALUES ('34');
INSERT INTO `test2` VALUES ('35');
INSERT INTO `test2` VALUES ('36');
INSERT INTO `test2` VALUES ('37');
INSERT INTO `test2` VALUES ('38');
INSERT INTO `test2` VALUES ('39');
INSERT INTO `test2` VALUES ('40');
INSERT INTO `test2` VALUES ('41');
INSERT INTO `test2` VALUES ('42');
INSERT INTO `test2` VALUES ('43');
INSERT INTO `test2` VALUES ('44');
INSERT INTO `test2` VALUES ('45');
INSERT INTO `test2` VALUES ('46');
INSERT INTO `test2` VALUES ('47');
INSERT INTO `test2` VALUES ('48');
INSERT INTO `test2` VALUES ('49');
INSERT INTO `test2` VALUES ('50');
INSERT INTO `test2` VALUES ('51');
INSERT INTO `test2` VALUES ('52');
INSERT INTO `test2` VALUES ('53');
INSERT INTO `test2` VALUES ('54');
INSERT INTO `test2` VALUES ('55');
INSERT INTO `test2` VALUES ('56');
INSERT INTO `test2` VALUES ('57');
INSERT INTO `test2` VALUES ('58');
INSERT INTO `test2` VALUES ('59');
INSERT INTO `test2` VALUES ('60');
INSERT INTO `test2` VALUES ('61');
INSERT INTO `test2` VALUES ('62');
INSERT INTO `test2` VALUES ('63');
INSERT INTO `test2` VALUES ('64');
INSERT INTO `test2` VALUES ('65');
INSERT INTO `test2` VALUES ('66');
INSERT INTO `test2` VALUES ('67');
INSERT INTO `test2` VALUES ('68');
INSERT INTO `test2` VALUES ('69');
INSERT INTO `test2` VALUES ('70');
INSERT INTO `test2` VALUES ('71');
INSERT INTO `test2` VALUES ('72');
INSERT INTO `test2` VALUES ('73');
INSERT INTO `test2` VALUES ('74');
INSERT INTO `test2` VALUES ('75');
INSERT INTO `test2` VALUES ('76');
INSERT INTO `test2` VALUES ('77');
INSERT INTO `test2` VALUES ('78');
INSERT INTO `test2` VALUES ('79');
INSERT INTO `test2` VALUES ('80');
INSERT INTO `test2` VALUES ('81');
INSERT INTO `test2` VALUES ('82');
INSERT INTO `test2` VALUES ('83');
INSERT INTO `test2` VALUES ('84');
INSERT INTO `test2` VALUES ('85');
INSERT INTO `test2` VALUES ('86');
INSERT INTO `test2` VALUES ('87');
INSERT INTO `test2` VALUES ('88');
INSERT INTO `test2` VALUES ('89');
INSERT INTO `test2` VALUES ('90');
INSERT INTO `test2` VALUES ('91');
INSERT INTO `test2` VALUES ('92');
INSERT INTO `test2` VALUES ('93');
INSERT INTO `test2` VALUES ('94');
INSERT INTO `test2` VALUES ('95');
INSERT INTO `test2` VALUES ('96');
INSERT INTO `test2` VALUES ('97');
INSERT INTO `test2` VALUES ('98');
INSERT INTO `test2` VALUES ('99');
INSERT INTO `test2` VALUES ('100');
INSERT INTO `test2` VALUES ('101');
INSERT INTO `test2` VALUES ('102');
INSERT INTO `test2` VALUES ('103');
INSERT INTO `test2` VALUES ('104');
INSERT INTO `test2` VALUES ('105');
INSERT INTO `test2` VALUES ('106');
INSERT INTO `test2` VALUES ('107');
INSERT INTO `test2` VALUES ('108');
INSERT INTO `test2` VALUES ('109');
INSERT INTO `test2` VALUES ('110');
INSERT INTO `test2` VALUES ('111');
INSERT INTO `test2` VALUES ('112');
INSERT INTO `test2` VALUES ('113');
INSERT INTO `test2` VALUES ('114');
INSERT INTO `test2` VALUES ('115');
INSERT INTO `test2` VALUES ('116');
INSERT INTO `test2` VALUES ('117');
INSERT INTO `test2` VALUES ('118');
INSERT INTO `test2` VALUES ('119');
INSERT INTO `test2` VALUES ('120');
INSERT INTO `test2` VALUES ('121');
INSERT INTO `test2` VALUES ('122');
INSERT INTO `test2` VALUES ('123');
INSERT INTO `test2` VALUES ('124');
INSERT INTO `test2` VALUES ('125');
INSERT INTO `test2` VALUES ('126');
INSERT INTO `test2` VALUES ('127');
INSERT INTO `test2` VALUES ('128');
INSERT INTO `test2` VALUES ('129');
INSERT INTO `test2` VALUES ('130');
INSERT INTO `test2` VALUES ('131');
INSERT INTO `test2` VALUES ('132');
INSERT INTO `test2` VALUES ('133');
INSERT INTO `test2` VALUES ('134');
INSERT INTO `test2` VALUES ('135');
INSERT INTO `test2` VALUES ('136');
INSERT INTO `test2` VALUES ('137');
INSERT INTO `test2` VALUES ('138');
INSERT INTO `test2` VALUES ('139');
INSERT INTO `test2` VALUES ('140');
INSERT INTO `test2` VALUES ('141');
INSERT INTO `test2` VALUES ('142');
INSERT INTO `test2` VALUES ('143');
INSERT INTO `test2` VALUES ('144');
INSERT INTO `test2` VALUES ('145');
INSERT INTO `test2` VALUES ('146');
INSERT INTO `test2` VALUES ('147');
INSERT INTO `test2` VALUES ('148');
INSERT INTO `test2` VALUES ('149');
INSERT INTO `test2` VALUES ('150');
INSERT INTO `test2` VALUES ('151');
INSERT INTO `test2` VALUES ('152');
INSERT INTO `test2` VALUES ('153');
INSERT INTO `test2` VALUES ('154');
INSERT INTO `test2` VALUES ('155');
INSERT INTO `test2` VALUES ('156');
INSERT INTO `test2` VALUES ('157');
INSERT INTO `test2` VALUES ('158');
INSERT INTO `test2` VALUES ('159');
INSERT INTO `test2` VALUES ('160');
INSERT INTO `test2` VALUES ('161');
INSERT INTO `test2` VALUES ('162');
INSERT INTO `test2` VALUES ('163');
INSERT INTO `test2` VALUES ('164');
INSERT INTO `test2` VALUES ('165');
INSERT INTO `test2` VALUES ('166');
INSERT INTO `test2` VALUES ('167');
INSERT INTO `test2` VALUES ('168');
INSERT INTO `test2` VALUES ('169');
INSERT INTO `test2` VALUES ('170');
INSERT INTO `test2` VALUES ('171');
INSERT INTO `test2` VALUES ('172');
INSERT INTO `test2` VALUES ('173');
INSERT INTO `test2` VALUES ('174');
INSERT INTO `test2` VALUES ('175');
INSERT INTO `test2` VALUES ('176');
INSERT INTO `test2` VALUES ('177');
INSERT INTO `test2` VALUES ('178');
INSERT INTO `test2` VALUES ('179');
INSERT INTO `test2` VALUES ('180');
INSERT INTO `test2` VALUES ('181');
INSERT INTO `test2` VALUES ('182');
INSERT INTO `test2` VALUES ('183');
INSERT INTO `test2` VALUES ('184');
INSERT INTO `test2` VALUES ('185');
INSERT INTO `test2` VALUES ('186');
INSERT INTO `test2` VALUES ('187');
INSERT INTO `test2` VALUES ('188');
INSERT INTO `test2` VALUES ('189');
INSERT INTO `test2` VALUES ('190');
INSERT INTO `test2` VALUES ('191');
INSERT INTO `test2` VALUES ('192');
INSERT INTO `test2` VALUES ('193');
INSERT INTO `test2` VALUES ('194');
INSERT INTO `test2` VALUES ('195');
INSERT INTO `test2` VALUES ('196');
INSERT INTO `test2` VALUES ('197');
INSERT INTO `test2` VALUES ('198');
INSERT INTO `test2` VALUES ('199');
INSERT INTO `test2` VALUES ('200');
INSERT INTO `test2` VALUES ('201');
INSERT INTO `test2` VALUES ('202');
INSERT INTO `test2` VALUES ('203');
INSERT INTO `test2` VALUES ('204');
INSERT INTO `test2` VALUES ('205');
INSERT INTO `test2` VALUES ('206');
INSERT INTO `test2` VALUES ('207');
INSERT INTO `test2` VALUES ('208');
INSERT INTO `test2` VALUES ('209');
INSERT INTO `test2` VALUES ('210');
INSERT INTO `test2` VALUES ('211');
INSERT INTO `test2` VALUES ('212');
INSERT INTO `test2` VALUES ('213');
INSERT INTO `test2` VALUES ('214');
INSERT INTO `test2` VALUES ('215');
INSERT INTO `test2` VALUES ('216');
INSERT INTO `test2` VALUES ('217');
INSERT INTO `test2` VALUES ('218');
INSERT INTO `test2` VALUES ('219');
INSERT INTO `test2` VALUES ('220');
INSERT INTO `test2` VALUES ('221');
INSERT INTO `test2` VALUES ('222');
INSERT INTO `test2` VALUES ('223');
INSERT INTO `test2` VALUES ('224');
INSERT INTO `test2` VALUES ('225');
INSERT INTO `test2` VALUES ('226');
INSERT INTO `test2` VALUES ('227');
INSERT INTO `test2` VALUES ('228');
INSERT INTO `test2` VALUES ('229');
INSERT INTO `test2` VALUES ('230');
INSERT INTO `test2` VALUES ('231');
INSERT INTO `test2` VALUES ('232');
INSERT INTO `test2` VALUES ('233');
INSERT INTO `test2` VALUES ('234');
INSERT INTO `test2` VALUES ('235');
INSERT INTO `test2` VALUES ('236');
INSERT INTO `test2` VALUES ('237');
INSERT INTO `test2` VALUES ('238');
INSERT INTO `test2` VALUES ('239');
INSERT INTO `test2` VALUES ('240');
INSERT INTO `test2` VALUES ('241');
INSERT INTO `test2` VALUES ('242');
INSERT INTO `test2` VALUES ('243');
INSERT INTO `test2` VALUES ('244');
INSERT INTO `test2` VALUES ('245');
INSERT INTO `test2` VALUES ('246');
INSERT INTO `test2` VALUES ('247');
INSERT INTO `test2` VALUES ('248');
INSERT INTO `test2` VALUES ('249');
INSERT INTO `test2` VALUES ('250');
INSERT INTO `test2` VALUES ('251');
INSERT INTO `test2` VALUES ('252');
INSERT INTO `test2` VALUES ('253');
INSERT INTO `test2` VALUES ('254');
INSERT INTO `test2` VALUES ('255');
INSERT INTO `test2` VALUES ('256');
INSERT INTO `test2` VALUES ('257');
INSERT INTO `test2` VALUES ('258');
INSERT INTO `test2` VALUES ('259');
INSERT INTO `test2` VALUES ('260');
INSERT INTO `test2` VALUES ('261');
INSERT INTO `test2` VALUES ('262');
INSERT INTO `test2` VALUES ('263');
INSERT INTO `test2` VALUES ('264');
INSERT INTO `test2` VALUES ('265');
INSERT INTO `test2` VALUES ('266');
INSERT INTO `test2` VALUES ('267');
INSERT INTO `test2` VALUES ('268');
INSERT INTO `test2` VALUES ('269');
INSERT INTO `test2` VALUES ('270');
INSERT INTO `test2` VALUES ('271');
INSERT INTO `test2` VALUES ('272');
INSERT INTO `test2` VALUES ('273');
INSERT INTO `test2` VALUES ('274');
INSERT INTO `test2` VALUES ('275');
INSERT INTO `test2` VALUES ('276');
INSERT INTO `test2` VALUES ('277');
INSERT INTO `test2` VALUES ('278');
INSERT INTO `test2` VALUES ('279');
INSERT INTO `test2` VALUES ('280');
INSERT INTO `test2` VALUES ('281');
INSERT INTO `test2` VALUES ('282');
INSERT INTO `test2` VALUES ('283');
INSERT INTO `test2` VALUES ('284');
INSERT INTO `test2` VALUES ('285');
INSERT INTO `test2` VALUES ('286');
INSERT INTO `test2` VALUES ('287');
INSERT INTO `test2` VALUES ('288');
INSERT INTO `test2` VALUES ('289');
INSERT INTO `test2` VALUES ('290');
INSERT INTO `test2` VALUES ('291');
INSERT INTO `test2` VALUES ('292');
INSERT INTO `test2` VALUES ('293');
INSERT INTO `test2` VALUES ('294');
INSERT INTO `test2` VALUES ('295');
INSERT INTO `test2` VALUES ('296');
INSERT INTO `test2` VALUES ('297');
INSERT INTO `test2` VALUES ('298');
INSERT INTO `test2` VALUES ('299');
INSERT INTO `test2` VALUES ('300');
INSERT INTO `test2` VALUES ('301');
INSERT INTO `test2` VALUES ('302');
INSERT INTO `test2` VALUES ('303');
INSERT INTO `test2` VALUES ('304');
INSERT INTO `test2` VALUES ('305');
INSERT INTO `test2` VALUES ('306');
INSERT INTO `test2` VALUES ('307');
INSERT INTO `test2` VALUES ('308');
INSERT INTO `test2` VALUES ('309');
INSERT INTO `test2` VALUES ('310');
INSERT INTO `test2` VALUES ('311');
INSERT INTO `test2` VALUES ('312');
INSERT INTO `test2` VALUES ('313');
INSERT INTO `test2` VALUES ('314');
INSERT INTO `test2` VALUES ('315');
INSERT INTO `test2` VALUES ('316');
INSERT INTO `test2` VALUES ('317');
INSERT INTO `test2` VALUES ('318');
INSERT INTO `test2` VALUES ('319');
INSERT INTO `test2` VALUES ('320');
INSERT INTO `test2` VALUES ('321');
INSERT INTO `test2` VALUES ('322');
INSERT INTO `test2` VALUES ('323');
INSERT INTO `test2` VALUES ('324');
INSERT INTO `test2` VALUES ('325');
INSERT INTO `test2` VALUES ('326');
INSERT INTO `test2` VALUES ('327');
INSERT INTO `test2` VALUES ('328');
INSERT INTO `test2` VALUES ('329');
INSERT INTO `test2` VALUES ('330');
INSERT INTO `test2` VALUES ('331');
INSERT INTO `test2` VALUES ('332');
INSERT INTO `test2` VALUES ('333');
INSERT INTO `test2` VALUES ('334');
INSERT INTO `test2` VALUES ('335');
INSERT INTO `test2` VALUES ('336');
INSERT INTO `test2` VALUES ('337');
INSERT INTO `test2` VALUES ('338');
INSERT INTO `test2` VALUES ('339');
INSERT INTO `test2` VALUES ('340');
INSERT INTO `test2` VALUES ('341');
INSERT INTO `test2` VALUES ('342');
INSERT INTO `test2` VALUES ('343');
INSERT INTO `test2` VALUES ('344');
INSERT INTO `test2` VALUES ('345');
INSERT INTO `test2` VALUES ('346');
INSERT INTO `test2` VALUES ('347');
INSERT INTO `test2` VALUES ('348');
INSERT INTO `test2` VALUES ('349');
INSERT INTO `test2` VALUES ('350');
INSERT INTO `test2` VALUES ('351');
INSERT INTO `test2` VALUES ('352');
INSERT INTO `test2` VALUES ('353');
INSERT INTO `test2` VALUES ('354');
INSERT INTO `test2` VALUES ('355');
INSERT INTO `test2` VALUES ('356');
INSERT INTO `test2` VALUES ('357');
INSERT INTO `test2` VALUES ('358');
INSERT INTO `test2` VALUES ('359');
INSERT INTO `test2` VALUES ('360');
INSERT INTO `test2` VALUES ('361');
INSERT INTO `test2` VALUES ('362');
INSERT INTO `test2` VALUES ('363');
INSERT INTO `test2` VALUES ('364');
INSERT INTO `test2` VALUES ('365');
INSERT INTO `test2` VALUES ('366');
INSERT INTO `test2` VALUES ('367');
INSERT INTO `test2` VALUES ('368');
INSERT INTO `test2` VALUES ('369');
INSERT INTO `test2` VALUES ('370');
INSERT INTO `test2` VALUES ('371');
INSERT INTO `test2` VALUES ('372');
INSERT INTO `test2` VALUES ('373');
INSERT INTO `test2` VALUES ('374');
INSERT INTO `test2` VALUES ('375');
INSERT INTO `test2` VALUES ('376');
INSERT INTO `test2` VALUES ('377');
INSERT INTO `test2` VALUES ('378');
INSERT INTO `test2` VALUES ('379');
INSERT INTO `test2` VALUES ('380');
INSERT INTO `test2` VALUES ('381');
INSERT INTO `test2` VALUES ('382');
INSERT INTO `test2` VALUES ('383');
INSERT INTO `test2` VALUES ('384');
INSERT INTO `test2` VALUES ('385');
INSERT INTO `test2` VALUES ('386');
INSERT INTO `test2` VALUES ('387');
INSERT INTO `test2` VALUES ('388');
INSERT INTO `test2` VALUES ('389');
INSERT INTO `test2` VALUES ('390');
INSERT INTO `test2` VALUES ('391');
INSERT INTO `test2` VALUES ('392');
INSERT INTO `test2` VALUES ('393');
INSERT INTO `test2` VALUES ('394');
INSERT INTO `test2` VALUES ('395');
INSERT INTO `test2` VALUES ('396');
INSERT INTO `test2` VALUES ('397');
INSERT INTO `test2` VALUES ('398');
INSERT INTO `test2` VALUES ('399');
INSERT INTO `test2` VALUES ('400');
INSERT INTO `test2` VALUES ('401');
INSERT INTO `test2` VALUES ('402');
INSERT INTO `test2` VALUES ('403');
INSERT INTO `test2` VALUES ('404');
INSERT INTO `test2` VALUES ('405');
INSERT INTO `test2` VALUES ('406');
INSERT INTO `test2` VALUES ('407');
INSERT INTO `test2` VALUES ('408');
INSERT INTO `test2` VALUES ('409');
INSERT INTO `test2` VALUES ('410');
INSERT INTO `test2` VALUES ('411');
INSERT INTO `test2` VALUES ('412');
INSERT INTO `test2` VALUES ('413');
INSERT INTO `test2` VALUES ('414');
INSERT INTO `test2` VALUES ('415');
INSERT INTO `test2` VALUES ('416');
INSERT INTO `test2` VALUES ('417');
INSERT INTO `test2` VALUES ('418');
INSERT INTO `test2` VALUES ('419');
INSERT INTO `test2` VALUES ('420');
INSERT INTO `test2` VALUES ('421');
INSERT INTO `test2` VALUES ('422');
INSERT INTO `test2` VALUES ('423');
INSERT INTO `test2` VALUES ('424');
INSERT INTO `test2` VALUES ('425');
INSERT INTO `test2` VALUES ('426');
INSERT INTO `test2` VALUES ('427');
INSERT INTO `test2` VALUES ('428');
INSERT INTO `test2` VALUES ('429');
INSERT INTO `test2` VALUES ('430');
INSERT INTO `test2` VALUES ('431');
INSERT INTO `test2` VALUES ('432');
INSERT INTO `test2` VALUES ('433');
INSERT INTO `test2` VALUES ('434');
INSERT INTO `test2` VALUES ('435');
INSERT INTO `test2` VALUES ('436');
INSERT INTO `test2` VALUES ('437');
INSERT INTO `test2` VALUES ('438');
INSERT INTO `test2` VALUES ('439');
INSERT INTO `test2` VALUES ('440');
INSERT INTO `test2` VALUES ('441');
INSERT INTO `test2` VALUES ('442');
INSERT INTO `test2` VALUES ('443');
INSERT INTO `test2` VALUES ('444');
INSERT INTO `test2` VALUES ('445');
INSERT INTO `test2` VALUES ('446');
INSERT INTO `test2` VALUES ('447');
INSERT INTO `test2` VALUES ('448');
INSERT INTO `test2` VALUES ('449');
INSERT INTO `test2` VALUES ('450');
INSERT INTO `test2` VALUES ('451');
INSERT INTO `test2` VALUES ('452');
INSERT INTO `test2` VALUES ('453');
INSERT INTO `test2` VALUES ('454');
INSERT INTO `test2` VALUES ('455');
INSERT INTO `test2` VALUES ('456');
INSERT INTO `test2` VALUES ('457');
INSERT INTO `test2` VALUES ('458');
INSERT INTO `test2` VALUES ('459');
INSERT INTO `test2` VALUES ('460');
INSERT INTO `test2` VALUES ('461');
INSERT INTO `test2` VALUES ('462');
INSERT INTO `test2` VALUES ('463');
INSERT INTO `test2` VALUES ('464');
INSERT INTO `test2` VALUES ('465');
INSERT INTO `test2` VALUES ('466');
INSERT INTO `test2` VALUES ('467');
INSERT INTO `test2` VALUES ('468');
INSERT INTO `test2` VALUES ('469');
INSERT INTO `test2` VALUES ('470');
INSERT INTO `test2` VALUES ('471');
INSERT INTO `test2` VALUES ('472');
INSERT INTO `test2` VALUES ('473');
INSERT INTO `test2` VALUES ('474');
INSERT INTO `test2` VALUES ('475');
INSERT INTO `test2` VALUES ('476');
INSERT INTO `test2` VALUES ('477');
INSERT INTO `test2` VALUES ('478');
INSERT INTO `test2` VALUES ('479');
INSERT INTO `test2` VALUES ('480');
INSERT INTO `test2` VALUES ('481');
INSERT INTO `test2` VALUES ('482');
INSERT INTO `test2` VALUES ('483');
INSERT INTO `test2` VALUES ('484');
INSERT INTO `test2` VALUES ('485');
INSERT INTO `test2` VALUES ('486');
INSERT INTO `test2` VALUES ('487');
INSERT INTO `test2` VALUES ('488');
INSERT INTO `test2` VALUES ('489');
INSERT INTO `test2` VALUES ('490');
INSERT INTO `test2` VALUES ('491');
INSERT INTO `test2` VALUES ('492');
INSERT INTO `test2` VALUES ('493');
INSERT INTO `test2` VALUES ('494');
INSERT INTO `test2` VALUES ('495');
INSERT INTO `test2` VALUES ('496');
INSERT INTO `test2` VALUES ('497');
INSERT INTO `test2` VALUES ('498');
INSERT INTO `test2` VALUES ('499');
INSERT INTO `test2` VALUES ('500');

-- ----------------------------
-- Table structure for `user`
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(20) NOT NULL,
  `passwd` char(32) NOT NULL,
  `email` varchar(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('11', 'imooc3', 'imooc3', 'imooc3@imooc3.com');
INSERT INTO `user` VALUES ('12', 'imooc111', 'imooc222', 'im444@123.com');
INSERT INTO `user` VALUES ('13', 'test', 'test', 'test@test.com');

-- ----------------------------
-- Table structure for `useraccount`
-- ----------------------------
DROP TABLE IF EXISTS `useraccount`;
CREATE TABLE `useraccount` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(20) NOT NULL,
  `money` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of useraccount
-- ----------------------------
INSERT INTO `useraccount` VALUES ('1', 'imooc', '8000.00');
INSERT INTO `useraccount` VALUES ('2', 'king', '7000.00');

-- ----------------------------
-- Procedure structure for `test1`
-- ----------------------------
DROP PROCEDURE IF EXISTS `test1`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `test1`()
BEGIN 
	SELECT * FROM user;
	SELECT * FROM userAccount;
END
;;
DELIMITER ;
